### ISSUE TITLE
library: expose request headers and body

### ISSUE THREAD

**Issue by mullender** [shazow/gohttplib#11]
I was trying out `gohttplib` after reading the blog post, which was very informative and detailed.

For the simple experiment I wanted to do (accept webhook triggers) I need access to the request headers and request body.

**Comment by shazow** [comment]
I'd be happy to accept pull requests that expose more of the go http functionality. I have no plans to work on it myself at this time. :)

**Comment by mullender** [comment]
Pull request opened :)
I totally understand not wanting to spend too much time on your end.

**Comment by mullender** [comment]
Will you publish this change to PyPI? That would be awesome.

Thanks for the quick turnaround on the PR.

**Comment by shazow** [comment]
Honestly I would avoid using the PyPI version; it's mostly there for demo purposes so it's targeting just a single platform. Particularly it's not possible to publish all the necessary pre-compiled OS/arch combos on PyPI. I would suggest vendoring it instead.

**Comment by mullender** [comment]
Ok, got it!

By the way, does the benchmark fail to complete for you, when you make more than 16,300 requests? For me the whole python server hangs, not even responding to control-C. For me that reproduces 100%. Wondering if it is just my machine

**Comment by shazow** [comment]
Hmmm, its been a while (I don't have an env setup right now) but if I recall, it _was_ a bit flakey and I never got around to cleaning it up. I suspect probably memory leaks, the `C.*` variables we're using need to be manually released.

**Comment by mullender** [comment]
that would do it, I just noticed the memory steadily increasing. I will see what I can do for you.
