### ISSUE TITLE
Unable to run benchmark past ~16,300 requests

### ISSUE THREAD

**Issue by mullender** [shazow/gohttplib#13]
As discussed in #11, I encountered the following issue: after about 16,300 requests created by the benchmark tool `ab` the server 'hangs'. This happens regardless of the concurrency

The failing command:

```
> ab -n 20000 -c 1 -s 5  http://127.0.0.1:5000/
...
Completed 16000 requests
apr_pollset_poll: The timeout specified has expired (70007)
Total of 16280 requests completed
```

When enabling `keep-alive` from `ab` the command does complete (`-k`), even with 10x more requests:

```
> ab -n 200000 -c 1 -s 5  -k http://127.0.0.1:5000/
...
Finished 200000 requests
...
```

_Note, the memory leak #14 is not causing this issue._

**Comment by shazow** [comment]
Hm so #15 does not fix this?

**Comment by mullender** [comment]
Unfortunately not :(
It seems to happen around 2^14 requests 

I am going to try it against the default golang webserver, and binary search my way to where the problem occurs.

**Comment by shazow** [comment]
Fascinating, looking forward to your investigation! :)

**Comment by mullender** [comment]
Results so far (seems like an issue with `go version go1.6.2 darwin/amd64` or `ab 2.3`)

file `serve.go`

```
package main

import (
    "fmt"
    "net/http"
)

func index(w http.ResponseWriter, req *http.Request) {
    fmt.Fprintf(w, "Hello, world.\n")
}

func main() {
    http.HandleFunc("/", index)
    http.ListenAndServe("127.0.0.1:5000", nil)
}
```

`» go run serve.go`

```
» ab -n 20000 -c 1 -s 5  http://127.0.0.1:5000/
This is ApacheBench, Version 2.3 <$Revision: 1706008 $>
Copyright 1996 Adam Twiss, Zeus Technology Ltd, http://www.zeustech.net/
Licensed to The Apache Software Foundation, http://www.apache.org/

Benchmarking 127.0.0.1 (be patient)
Completed 2000 requests
Completed 4000 requests
Completed 6000 requests
Completed 8000 requests
Completed 10000 requests
Completed 12000 requests
Completed 14000 requests
Completed 16000 requests
apr_pollset_poll: The timeout specified has expired (70007)
Total of 16280 requests completed
```

**Comment by mullender** [comment]
Found it: https://github.com/golang/go/issues/66

**Comment by shazow** [comment]
Neat! So... not an issue then? :/

**Comment by mullender** [comment]
No issue in this repo, perhaps in the OSX or golang repo's :)

Closing the issue
