### ISSUE TITLE
gohttplib supports concurrent request processing

### ISSUE THREAD

**Issue by mullender** [shazow/gohttplib#16]
This is an interesting feature not clearly mentioned in your blog, or the README.

gohttplib supports concurrent request processing out of the box. For example a method that takes a second for every 10th invocation (see below). Will process 100 requests concurrently:

```
> ab -n 100 -c 100 -s 5 -k http://127.0.0.1:5000/
...
Time taken for tests:   1.009 seconds
...
```

The same test with flask takes 10 seconds, unless you pass `threaded=True`

The test method

```
@route('/')
    def index(w, req):
        global count
        if count % 10 == 0:
            foo = time.time()
            while time.time() < foo + 1:
                print "doing work"
        count += 1
        w.set_status(200)

        w.write(b"Hello, world.\n")
        pass
```

**Comment by shazow** [comment]
This is true. I thought it would be obvious because it's bindings to Go's runtime which is concurrent by default.

**Comment by mullender** [comment]
It sure was a pleasant surprise for me :)
