### ISSUE TITLE
tutorial/automation to wrap standard Go functions

### ISSUE THREAD

**Issue by techtonik** [shazow/gohttplib#17]
I found https://blog.heroku.com/see_python_see_python_go_go_python_go while looking at how can I call Go stdlib from Python. In many cases (time/date, exec, net) API seems more mature to me.

I found https://github.com/go-python/gopy but it is somewhat stalled and is not compatible with 1.6, so the question is - is it possible to write a tool that can wrap Go functions automatically, starting from more simple ones and gradually build up?

    expose time.Now() gogogo

Then in Python just:

    from gogogo import time
    print time.Now().String()

Just a fantasy. =) I know that it is complicated, takes a lot of time and requires [some specs](https://github.com/techtonik/pseps/blob/master/psep-0101.txt) to be written. Maybe there are already existing project like https://github.com/pybind/pybind11 that are more active.

**Comment by shazow** [comment]
It's certainly possible, and I have seen a few projects like the ones you mentioned which give it a whirl, but it's quite a bit of work. :)

**Comment by techtonik** [comment]
Fair enough. =)
